#配置druid数据源位置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: warehouse
      url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      enable: true
      validation-query: SELECT 'x' #验证链接
      filters: stat,wall
      #监控配置
      stat-view-servlet:
        allow:
        enabled: true
        login-username: hcl
        login-password: 123456
        url-pattern: /druid/*
        deny:
  #thymeleaf模版引擎配置
  thymeleaf:
    cache: false
    enabled: true
  #日期时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #热部署生效
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java


#mybatisPlus相关配置
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /resources/**
  login-url: /sys/toLogin
  log-out-url: /login/logout*
  authc-ulrs:
    - /**

#xxljob配置
xxl:
  job:
    accessToken:
    address: http://127.0.0.1:8080/xxl-job-admin
    #执行器名称
    appName: ware-house-job
    ip:
    port: 9999
    logretentiondays: 1
    logPath:
